# Generated by Django 3.2.8 on 2021-11-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
